---

- name: Add Neo4j service
  template:
    src: docker-neo4j.service
    dest: /etc/systemd/system/
    mode: 600
    owner: root
    group: root
  tags:
    - neo4j

- name: Start Neo4j
  service:
    name: docker-neo4j
    enabled: no
    state: stopped
    daemon_reload: yes
  tags:
    - neo4j

