---
# This playbook deploys a simple standalone JBoss server. 

- hosts: cislaves
  remote_user: fedora
  sudo: yes

  roles:
    - common
    - os1
    - jenkins-slave

- hosts: cimaster
  remote_user: fedora
  sudo: yes

  roles:
    - common
    - os1
    - jenkins

