---

# Additional packages required for some build
- name: Extra packages required on slaves
  dnf: name={{item}} state=present
  with_items:
    - wget
    - jq
    - sed
  tags:
    - extra-packages

- name: Docker engine
  dnf: name={{item}} state=latest
  with_items:
    - python-docker-py
    - docker-engine
  tags:
    - docker

- name: Start Docker
  service: name=docker enabled=yes state=started
  tags:
    - docker

- name: Enable SERVICES Cmnd_Alias
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: 'Cmnd_Alias SERVICES'
    line: 'Cmnd_Alias SERVICES = /sbin/service, /sbin/chkconfig'
    validate: 'visudo -cf %s'
  tags:
    - services

- name: Give jenkins permission to run services
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^jenkins ALL='
    line: 'jenkins ALL=(ALL) NOPASSWD: SERVICES'
    validate: 'visudo -cf %s'
  tags:
    - services

- name: Give jenkins permission to run docker
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^jenkins ALL='
    line: 'jenkins ALL=(ALL) NOPASSWD: /usr/bin/docker'
    validate: 'visudo -cf %s'
  tags:
    - services

# Use the extra space on /mnt

- name: Create /mnt/.m2
  file: path=/mnt/.m2 owner=jenkins group=jenkins mode=0755 state=directory
  tags:
    - jenkins

- name: Create link /home/jenkins/.m2 to /mnt/.m2
  file: path=/home/jenkins/.m2 src=/mnt/.m2 owner=jenkins group=jenkins mode=0755 state=link force=yes
  tags:
    - jenkins

- name: Create /mnt/.gradle
  file: path=/mnt/.gradle owner=jenkins group=jenkins mode=0755 state=directory
  tags:
    - jenkins

- name: Create link /home/jenkins/.gradle to /mnt/.gradle
  file: path=/home/jenkins/.gradle src=/mnt/.gradle owner=jenkins group=jenkins mode=0755 state=link force=yes
  tags:
    - jenkins

- name: Create /mnt/jenkins-workdir
  file: path=/mnt/jenkins-workdir owner=jenkins group=jenkins mode=0755 state=directory
  tags:
    - jenkins

- name: Create link /var/lib/jenkins to /mnt/jenkins-workdir
  file: path=/var/lib/jenkins src=/mnt/jenkins-workdir owner=jenkins group=jenkins mode=0755 state=link force=yes
  tags:
    - jenkins

- name: Add passwordless connection for jenkins
  copy: src=authorized_keys dest=/home/jenkins/.ssh/authorized_keys mode=0600 owner=jenkins group=jenkins
  tags:
    - jenkins

- name: Add Couchdb service 
  copy: src=couchdb/docker-couchdb.service dest=/etc/systemd/system/ mode=0600 owner=root group=root
  tags:
    - couchdb

- name: Start CouchDB
  service:
    name: docker-couchdb
    enabled: no
    state: stopped
    daemon_reload: yes
  tags:
    - couchdb

- name: Add Cassandra service 
  copy: src=cassandra/docker-cassandra.service dest=/etc/systemd/system/ mode=0600 owner=root group=root
  tags:
    - cassandra

- name: Start Cassandra
  service:
    name: docker-cassandra
    enabled: no
    state: stopped
    daemon_reload: yes
  tags:
    - cassandra

# Some slaves need to run rsync on the master,
# this will ensure master is added to the known_host
# The ssh-keyscan approach (controversial!) is inspired from: http://hakunin.com/six-ansible-practices
- name: Ensure cimaster is a known host
  lineinfile:
    dest: /home/jenkins/.ssh/known_hosts
    state: present
    create: yes
    owner: jenkins
    group: jenkins
    mode: 0600
    line: "{{ lookup('pipe', 'ssh-keyscan -t ecdsa ' + groups['cimaster'][0]) }}"
    regexp: "^{{groups['cimaster'][0]}}"
  tags:
    - crosskeyauthentication
    - create-known-hosts

- name: Ensure ci.hibernate.org is a known host
  lineinfile:
    dest: /home/jenkins/.ssh/cihibernate-knownhosts
    state: present
    create: yes
    owner: jenkins
    group: jenkins
    mode: 0600
    line: "{{ lookup('pipe', 'ssh-keyscan -t ecdsa ci.hibernate.org') }}"
    regexp: "^ci.hibernate.org"
  tags:
    - crosskeyauthentication

- name: Ensure in.relation.to is a known host
  lineinfile:
    dest: /home/jenkins/.ssh/inrelationto-knownhosts
    create: yes
    state: present
    owner: jenkins
    group: jenkins
    mode: 0600
    line: "{{ lookup('pipe', 'ssh-keyscan -t ecdsa in.relation.to') }}"
    regexp: "^in.relation.to"
  tags:
    - crosskeyauthentication

