

- hosts: cislaves
  remote_user: fedora
  become: yes
  tasks:
    - name: Stop Cassandra
      command: pkill -9 -u cassandra
      ignore_errors: yes

    - name: Uninstall Cassandra
      dnf: name=cassandra30 state=absent
      tags:
        - packages

    - name: Delete folders
      file: path={{item}} state=absent
      with_items:
        - /etc/cassandra
        - /var/log/cassandra
        - /var/lib/cassandra
        - /var/run/cassandra
        - /var/lock/subsys/cassandra
