---

- name: Restart Network
  service: name=network state=restarted args=eth0
  async: 1
  poll: 0
  ignore_errors: yes
  become: yes
  tags:
    - network

- name: Network Restarted
  local_action:
    module: wait_for
         host={{ inventory_hostname }}
         port=22
         delay=1
         timeout=300
    become: no
  tags:
    - network

- name: Restart sshd
  service: name=sshd enabled=yes state=restarted
  tags:
    - password-auth
