---

- name: Restart server
  shell: sleep 2 && shutdown -r now "Reboot triggered by Ansible"
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true

- name: Wait for server to restart
  local_action: wait_for host={{ inventory_hostname }} state=started delay=10 timeout=300 port=22
  sudo: false

- name: Restart journald
  service: name=systemd-journald enabled=yes state=restarted
